### ISSUE TITLE
Improving the legibility of text and improving UX

### ISSUE THREAD

**Issue by samalsubrat** [Bitbox-Connect/Bitbox#12] opened 2024-10-06 16:38 UTC
### Issue: 
- The text on the landing page in light-mode is hardly legible. The font-width is too small compared to industry standard.
- The text on the cards are also not aligned perfectly. The heads of each card should be aligned on a same level, and the description on an other level to improve UX and follow better design practices.
![image](https://github.com/user-attachments/assets/98c48efa-f277-4394-bc25-51ab65b8f2ee)

### Fix:
- Playing around with font-width in CSS to make it more legible. 
- Doing some more CSS changes like hover effects to improve the user experience

### Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags so I can start working on its UX.

**Comment by Anuj3553** [comment] 2024-10-06 16:52
Hyy @samalsubrat,

First, don't worry about the tags. We will assign it to you after you complete the task. Once the task is completed, we will give you the tags.

**Comment by Anuj3553** [comment] 2024-10-06 16:54
Hyy @samalsubrat,

We will give you remaining tags once the issue is completed. If you have any questions or additional information, free feel to share with us.

**Comment by samalsubrat** [comment] 2024-10-06 16:54
Sure, working on this.

**Comment by Anuj3553** [comment] 2024-10-09 15:55
Hyy @Hh440, Can you do star mark this repo?

**Closed** 2024-10-09 15:57 UTC
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest
